package com.zy1401_402.oaSystem.entity;

import java.io.Serializable;

public class courses implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.course_id
     *
     * @mbggenerated
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.course_name
     *
     * @mbggenerated
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.course_describe
     *
     * @mbggenerated
     */
    private String courseDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.course_property
     *
     * @mbggenerated
     */
    private String courseProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table courses
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.course_id
     *
     * @return the value of courses.course_id
     *
     * @mbggenerated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.course_id
     *
     * @param courseId the value for courses.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.course_name
     *
     * @return the value of courses.course_name
     *
     * @mbggenerated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.course_name
     *
     * @param courseName the value for courses.course_name
     *
     * @mbggenerated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.course_describe
     *
     * @return the value of courses.course_describe
     *
     * @mbggenerated
     */
    public String getCourseDescribe() {
        return courseDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.course_describe
     *
     * @param courseDescribe the value for courses.course_describe
     *
     * @mbggenerated
     */
    public void setCourseDescribe(String courseDescribe) {
        this.courseDescribe = courseDescribe == null ? null : courseDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.course_property
     *
     * @return the value of courses.course_property
     *
     * @mbggenerated
     */
    public String getCourseProperty() {
        return courseProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.course_property
     *
     * @param courseProperty the value for courses.course_property
     *
     * @mbggenerated
     */
    public void setCourseProperty(String courseProperty) {
        this.courseProperty = courseProperty == null ? null : courseProperty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        courses other = (courses) that;
        return (this.getCourseId() == null ? other.getCourseId() == null : this.getCourseId().equals(other.getCourseId()))
            && (this.getCourseName() == null ? other.getCourseName() == null : this.getCourseName().equals(other.getCourseName()))
            && (this.getCourseDescribe() == null ? other.getCourseDescribe() == null : this.getCourseDescribe().equals(other.getCourseDescribe()))
            && (this.getCourseProperty() == null ? other.getCourseProperty() == null : this.getCourseProperty().equals(other.getCourseProperty()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCourseId() == null) ? 0 : getCourseId().hashCode());
        result = prime * result + ((getCourseName() == null) ? 0 : getCourseName().hashCode());
        result = prime * result + ((getCourseDescribe() == null) ? 0 : getCourseDescribe().hashCode());
        result = prime * result + ((getCourseProperty() == null) ? 0 : getCourseProperty().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", courseId=").append(courseId);
        sb.append(", courseName=").append(courseName);
        sb.append(", courseDescribe=").append(courseDescribe);
        sb.append(", courseProperty=").append(courseProperty);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}