package com.zy1401_402.oaSystem.entity;

import java.io.Serializable;

public class person implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_id
     *
     * @mbggenerated
     */
    private String personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_password
     *
     * @mbggenerated
     */
    private String personPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_name
     *
     * @mbggenerated
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_role
     *
     * @mbggenerated
     */
    private String personRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_department
     *
     * @mbggenerated
     */
    private String personDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_phone
     *
     * @mbggenerated
     */
    private String personPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_email
     *
     * @mbggenerated
     */
    private String personEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_id
     *
     * @return the value of person.person_id
     *
     * @mbggenerated
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_id
     *
     * @param personId the value for person.person_id
     *
     * @mbggenerated
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_password
     *
     * @return the value of person.person_password
     *
     * @mbggenerated
     */
    public String getPersonPassword() {
        return personPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_password
     *
     * @param personPassword the value for person.person_password
     *
     * @mbggenerated
     */
    public void setPersonPassword(String personPassword) {
        this.personPassword = personPassword == null ? null : personPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_name
     *
     * @return the value of person.person_name
     *
     * @mbggenerated
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_name
     *
     * @param personName the value for person.person_name
     *
     * @mbggenerated
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_role
     *
     * @return the value of person.person_role
     *
     * @mbggenerated
     */
    public String getPersonRole() {
        return personRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_role
     *
     * @param personRole the value for person.person_role
     *
     * @mbggenerated
     */
    public void setPersonRole(String personRole) {
        this.personRole = personRole == null ? null : personRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_department
     *
     * @return the value of person.person_department
     *
     * @mbggenerated
     */
    public String getPersonDepartment() {
        return personDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_department
     *
     * @param personDepartment the value for person.person_department
     *
     * @mbggenerated
     */
    public void setPersonDepartment(String personDepartment) {
        this.personDepartment = personDepartment == null ? null : personDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_phone
     *
     * @return the value of person.person_phone
     *
     * @mbggenerated
     */
    public String getPersonPhone() {
        return personPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_phone
     *
     * @param personPhone the value for person.person_phone
     *
     * @mbggenerated
     */
    public void setPersonPhone(String personPhone) {
        this.personPhone = personPhone == null ? null : personPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_email
     *
     * @return the value of person.person_email
     *
     * @mbggenerated
     */
    public String getPersonEmail() {
        return personEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_email
     *
     * @param personEmail the value for person.person_email
     *
     * @mbggenerated
     */
    public void setPersonEmail(String personEmail) {
        this.personEmail = personEmail == null ? null : personEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        person other = (person) that;
        return (this.getPersonId() == null ? other.getPersonId() == null : this.getPersonId().equals(other.getPersonId()))
            && (this.getPersonPassword() == null ? other.getPersonPassword() == null : this.getPersonPassword().equals(other.getPersonPassword()))
            && (this.getPersonName() == null ? other.getPersonName() == null : this.getPersonName().equals(other.getPersonName()))
            && (this.getPersonRole() == null ? other.getPersonRole() == null : this.getPersonRole().equals(other.getPersonRole()))
            && (this.getPersonDepartment() == null ? other.getPersonDepartment() == null : this.getPersonDepartment().equals(other.getPersonDepartment()))
            && (this.getPersonPhone() == null ? other.getPersonPhone() == null : this.getPersonPhone().equals(other.getPersonPhone()))
            && (this.getPersonEmail() == null ? other.getPersonEmail() == null : this.getPersonEmail().equals(other.getPersonEmail()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPersonId() == null) ? 0 : getPersonId().hashCode());
        result = prime * result + ((getPersonPassword() == null) ? 0 : getPersonPassword().hashCode());
        result = prime * result + ((getPersonName() == null) ? 0 : getPersonName().hashCode());
        result = prime * result + ((getPersonRole() == null) ? 0 : getPersonRole().hashCode());
        result = prime * result + ((getPersonDepartment() == null) ? 0 : getPersonDepartment().hashCode());
        result = prime * result + ((getPersonPhone() == null) ? 0 : getPersonPhone().hashCode());
        result = prime * result + ((getPersonEmail() == null) ? 0 : getPersonEmail().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", personId=").append(personId);
        sb.append(", personPassword=").append(personPassword);
        sb.append(", personName=").append(personName);
        sb.append(", personRole=").append(personRole);
        sb.append(", personDepartment=").append(personDepartment);
        sb.append(", personPhone=").append(personPhone);
        sb.append(", personEmail=").append(personEmail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}