package com.zy1401_402.oaSystem.entity;

import java.io.Serializable;

public class schedule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.course_number
     *
     * @mbggenerated
     */
    private Integer courseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.course_id
     *
     * @mbggenerated
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.course_name
     *
     * @mbggenerated
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.person_id
     *
     * @mbggenerated
     */
    private String personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.person_name
     *
     * @mbggenerated
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.course_stu_num
     *
     * @mbggenerated
     */
    private Integer courseStuNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.course_cycle
     *
     * @mbggenerated
     */
    private String courseCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.course_period
     *
     * @mbggenerated
     */
    private String coursePeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.course_date
     *
     * @mbggenerated
     */
    private String courseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.course_location
     *
     * @mbggenerated
     */
    private String courseLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.course_department
     *
     * @mbggenerated
     */
    private String courseDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.course_number
     *
     * @return the value of schedule.course_number
     *
     * @mbggenerated
     */
    public Integer getCourseNumber() {
        return courseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.course_number
     *
     * @param courseNumber the value for schedule.course_number
     *
     * @mbggenerated
     */
    public void setCourseNumber(Integer courseNumber) {
        this.courseNumber = courseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.course_id
     *
     * @return the value of schedule.course_id
     *
     * @mbggenerated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.course_id
     *
     * @param courseId the value for schedule.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.course_name
     *
     * @return the value of schedule.course_name
     *
     * @mbggenerated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.course_name
     *
     * @param courseName the value for schedule.course_name
     *
     * @mbggenerated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.person_id
     *
     * @return the value of schedule.person_id
     *
     * @mbggenerated
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.person_id
     *
     * @param personId the value for schedule.person_id
     *
     * @mbggenerated
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.person_name
     *
     * @return the value of schedule.person_name
     *
     * @mbggenerated
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.person_name
     *
     * @param personName the value for schedule.person_name
     *
     * @mbggenerated
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.course_stu_num
     *
     * @return the value of schedule.course_stu_num
     *
     * @mbggenerated
     */
    public Integer getCourseStuNum() {
        return courseStuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.course_stu_num
     *
     * @param courseStuNum the value for schedule.course_stu_num
     *
     * @mbggenerated
     */
    public void setCourseStuNum(Integer courseStuNum) {
        this.courseStuNum = courseStuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.course_cycle
     *
     * @return the value of schedule.course_cycle
     *
     * @mbggenerated
     */
    public String getCourseCycle() {
        return courseCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.course_cycle
     *
     * @param courseCycle the value for schedule.course_cycle
     *
     * @mbggenerated
     */
    public void setCourseCycle(String courseCycle) {
        this.courseCycle = courseCycle == null ? null : courseCycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.course_period
     *
     * @return the value of schedule.course_period
     *
     * @mbggenerated
     */
    public String getCoursePeriod() {
        return coursePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.course_period
     *
     * @param coursePeriod the value for schedule.course_period
     *
     * @mbggenerated
     */
    public void setCoursePeriod(String coursePeriod) {
        this.coursePeriod = coursePeriod == null ? null : coursePeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.course_date
     *
     * @return the value of schedule.course_date
     *
     * @mbggenerated
     */
    public String getCourseDate() {
        return courseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.course_date
     *
     * @param courseDate the value for schedule.course_date
     *
     * @mbggenerated
     */
    public void setCourseDate(String courseDate) {
        this.courseDate = courseDate == null ? null : courseDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.course_location
     *
     * @return the value of schedule.course_location
     *
     * @mbggenerated
     */
    public String getCourseLocation() {
        return courseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.course_location
     *
     * @param courseLocation the value for schedule.course_location
     *
     * @mbggenerated
     */
    public void setCourseLocation(String courseLocation) {
        this.courseLocation = courseLocation == null ? null : courseLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.course_department
     *
     * @return the value of schedule.course_department
     *
     * @mbggenerated
     */
    public String getCourseDepartment() {
        return courseDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.course_department
     *
     * @param courseDepartment the value for schedule.course_department
     *
     * @mbggenerated
     */
    public void setCourseDepartment(String courseDepartment) {
        this.courseDepartment = courseDepartment == null ? null : courseDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        schedule other = (schedule) that;
        return (this.getCourseNumber() == null ? other.getCourseNumber() == null : this.getCourseNumber().equals(other.getCourseNumber()))
            && (this.getCourseId() == null ? other.getCourseId() == null : this.getCourseId().equals(other.getCourseId()))
            && (this.getCourseName() == null ? other.getCourseName() == null : this.getCourseName().equals(other.getCourseName()))
            && (this.getPersonId() == null ? other.getPersonId() == null : this.getPersonId().equals(other.getPersonId()))
            && (this.getPersonName() == null ? other.getPersonName() == null : this.getPersonName().equals(other.getPersonName()))
            && (this.getCourseStuNum() == null ? other.getCourseStuNum() == null : this.getCourseStuNum().equals(other.getCourseStuNum()))
            && (this.getCourseCycle() == null ? other.getCourseCycle() == null : this.getCourseCycle().equals(other.getCourseCycle()))
            && (this.getCoursePeriod() == null ? other.getCoursePeriod() == null : this.getCoursePeriod().equals(other.getCoursePeriod()))
            && (this.getCourseDate() == null ? other.getCourseDate() == null : this.getCourseDate().equals(other.getCourseDate()))
            && (this.getCourseLocation() == null ? other.getCourseLocation() == null : this.getCourseLocation().equals(other.getCourseLocation()))
            && (this.getCourseDepartment() == null ? other.getCourseDepartment() == null : this.getCourseDepartment().equals(other.getCourseDepartment()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCourseNumber() == null) ? 0 : getCourseNumber().hashCode());
        result = prime * result + ((getCourseId() == null) ? 0 : getCourseId().hashCode());
        result = prime * result + ((getCourseName() == null) ? 0 : getCourseName().hashCode());
        result = prime * result + ((getPersonId() == null) ? 0 : getPersonId().hashCode());
        result = prime * result + ((getPersonName() == null) ? 0 : getPersonName().hashCode());
        result = prime * result + ((getCourseStuNum() == null) ? 0 : getCourseStuNum().hashCode());
        result = prime * result + ((getCourseCycle() == null) ? 0 : getCourseCycle().hashCode());
        result = prime * result + ((getCoursePeriod() == null) ? 0 : getCoursePeriod().hashCode());
        result = prime * result + ((getCourseDate() == null) ? 0 : getCourseDate().hashCode());
        result = prime * result + ((getCourseLocation() == null) ? 0 : getCourseLocation().hashCode());
        result = prime * result + ((getCourseDepartment() == null) ? 0 : getCourseDepartment().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", courseNumber=").append(courseNumber);
        sb.append(", courseId=").append(courseId);
        sb.append(", courseName=").append(courseName);
        sb.append(", personId=").append(personId);
        sb.append(", personName=").append(personName);
        sb.append(", courseStuNum=").append(courseStuNum);
        sb.append(", courseCycle=").append(courseCycle);
        sb.append(", coursePeriod=").append(coursePeriod);
        sb.append(", courseDate=").append(courseDate);
        sb.append(", courseLocation=").append(courseLocation);
        sb.append(", courseDepartment=").append(courseDepartment);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}