package com.zy1401_402.oaSystem.dao;

import com.zy1401_402.oaSystem.entity.leave_apply;

public interface leave_applyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_apply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer leaveNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_apply
     *
     * @mbggenerated
     */
    int insert(leave_apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_apply
     *
     * @mbggenerated
     */
    int insertSelective(leave_apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_apply
     *
     * @mbggenerated
     */
    leave_apply selectByPrimaryKey(Integer leaveNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(leave_apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(leave_apply record);
}